SELECT LENGTH ('SQL Expeert') LEN
FROM DUAL;

DESC DUAL;

SELECT
    *
FROM DUAL;

SELECT CONCAT (PLAYER_NAME, ' 축구선수') 선수명
FROM player;

SELECT PLAYER_NAME || ' 축구선수' 선수명
FROM player;

SELECT STADIUM_ID, DDD || ')' || TEL AS TEL, LENGTH (DDD || '-' || TEL) AS T_LEN
FROM STADIUM;

SELECT ENAME, ROUND(SAL / 12, 1) AS SAL_ROUND, TRUNC (SAL/ 12 , 1) AS SAL_TRUNC
FROM emp;


