SELECT team_id 팀ID , to_number(ZIP_CODE1, '999') + TO_NUMBER(ZIP_CODE2, '999') 우편번호합
FROM TEAM;

SELECT SYSDATE
FROM DUAL;

SELECT ename 사원명, hiredate 입사일자,
       EXTRACT (YEAR FROM HIREDATE) 입사년도,
       EXTRACT (MONTH FROM HIREDATE) 입사월,
       EXTRACT (DAY FROM HIREDATE) 입사일
FROM EMP;

SELECT TO_CHAR (SYSDATE, 'YYYY/MM/DD') 날짜,
       TO_CHAR (SYSDATE, 'YYYY.MON,DAY') 문자형
FROM DUAL;

SELECT ENAME,ROUND(SAL/12) SAL_ROUND, CEIL(SAL/12) SAL_CEIL
FROM EMP;