SELECT ENAME 사원명, DEPTNO 부서번호
    ,CASE MONTH WHEN 1 THEN SAL END AS M01, CASE MONTH WHEN 2 THEN SAL END AS M02
    ,CASE MONTH WHEN 3 THEN SAL END AS M03, CASE MONTH WHEN 4 THEN SAL END AS M04
    ,CASE MONTH WHEN 5 THEN SAL END AS M05, CASE MONTH WHEN 6 THEN SAL END AS M06
    ,CASE MONTH WHEN 7 THEN SAL END AS M07, CASE MONTH WHEN 8 THEN SAL END AS M08
    ,CASE MONTH WHEN 9 THEN SAL END AS M09, CASE MONTH WHEN 10 THEN SAL END AS M10
    ,CASE MONTH WHEN 11 THEN SAL END AS M11, CASE MONTH WHEN 12 THEN SAL END AS M12
FROM (SELECT ENAME, DEPTNO, EXTRACT (MONTH FROM HIREDATE) MONTH, SAL FROM EMP);

SELECT DEPTNO 부서번호
        ,AVG (CASE MONTH WHEN 1 THEN SAL END) AS M01, AVG (CASE MONTH WHEN 2 THEN SAL END) M02
        ,AVG (CASE MONTH WHEN 3 THEN SAL END) AS M03, AVG (CASE MONTH WHEN 2 THEN SAL END) M04
        ,AVG (CASE MONTH WHEN 5 THEN SAL END) AS M05, AVG (CASE MONTH WHEN 2 THEN SAL END) M06
        ,AVG (CASE MONTH WHEN 7 THEN SAL END) AS M07, AVG (CASE MONTH WHEN 2 THEN SAL END) M08
        ,AVG (CASE MONTH WHEN 9 THEN SAL END) AS M09, AVG (CASE MONTH WHEN 2 THEN SAL END) M10
        ,AVG (CASE MONTH WHEN 11 THEN SAL END) AS M11, AVG (CASE MONTH WHEN 2 THEN SAL END) M12
        FROM (SELECT ENAME, DEPTNO, EXTRACT (MONTH FROM HIREDATE) AS MONTH, SAL FROM EMP)
GROUP BY DEPTNO;

SELECT DEPTNO 부서번호
        , AVG (DECODE (MONTH, 1 , SAL)) M01, AVG (DECODE (MONTH, 2 ,SAL)) M02
        , AVG (DECODE (MONTH, 3 , SAL)) M03, AVG (DECODE (MONTH, 2 ,SAL)) M04
        , AVG (DECODE (MONTH, 5 , SAL)) M05, AVG (DECODE (MONTH, 2 ,SAL)) M06
        , AVG (DECODE (MONTH, 7 , SAL)) M07, AVG (DECODE (MONTH, 2 ,SAL)) M08
        , AVG (DECODE (MONTH, 9 , SAL)) M09, AVG (DECODE (MONTH, 2 ,SAL)) M10
        , AVG (DECODE (MONTH, 11 , SAL)) M11, AVG (DECODE (MONTH, 2 ,SAL)) M12
        FROM (SELECT ENAME, DEPTNO, EXTRACT (MONTH FROM HIREDATE) MONTH, SAL FROM EMP)
GROUP BY DEPTNO;

SELECT TEAM_ID
        , NVL (SUM (CASE POSITION WHEN 'FW' THEN 1 ELSE 0 END), 0) FW
        , NVL (SUM (CASE POSITION WHEN 'MF' THEN 1 ELSE 0 END), 0) MF
        , NVL (SUM (CASE POSITION WHEN 'DF' THEN 1 ELSE 0 END), 0) DF
        , NVL (SUM (CASE POSITION WHEN 'GK' THEN 1 ELSE 0 END), 0) GK
        , COUNT(*) SUM
        FROM PLAYER
GROUP BY TEAM_ID;

SELECT TEAM_ID
        , NVL (SUM (CASE POSITION WHEN 'FW' THEN 1 END), 0) FW
        , NVL (SUM (CASE POSITION WHEN 'MF' THEN 1 END), 0) MF
        , NVL (SUM (CASE POSITION WHEN 'DF' THEN 1 END), 0) DF
        , NVL (SUM (CASE POSITION WHEN 'GK' THEN 1 END), 0) GK
        , COUNT(*) SUM
        FROM PLAYER
GROUP BY TEAM_ID;

SELECT TEAM_ID
        , NVL (SUM (CASE WHEN POSITION = 'FW' THEN 1 END), 0) FW
        , NVL (SUM (CASE WHEN POSITION = 'MF' THEN 1 END), 0) MF
        , NVL (SUM (CASE WHEN POSITION = 'DF' THEN 1 END), 0) DF
        , NVL (SUM (CASE WHEN POSITION = 'GK' THEN 1 END), 0) GK
        , COUNT(*) SUM
        FROM PLAYER
GROUP BY TEAM_ID;

SELECT ROUND (AVG (CASE WHEN POSITION = 'MF' THEN HEIGHT END), 2) AS 미드필더
      ,ROUND (AVG (CASE WHEN POSITION = 'FW' THEN HEIGHT END), 2) AS 포워드
      ,ROUND (AVG (CASE WHEN POSITION = 'DF' THEN HEIGHT END), 2) AS 디펜더
      ,ROUND (AVG (CASE WHEN POSITION = 'GK' THEN HEIGHT END), 2) AS 골키퍼
      ,ROUND (AVG (HEIGHT), 2) 전체평균키
FROM PLAYER;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
    FROM PLAYER
ORDER BY PLAYER_NAME DESC;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
    FROM PLAYER
ORDER BY 포지션 DESC;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
    WHERE HEIGHT IS NOT NULL
ORDER BY HEIGHT DESC, BACK_NO;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
    FROM PLAYER
    WHERE BACK_NO IS NOT NULL
ORDER BY 3 DESC, 2 , 1;