SELECT DNAME, LOC , DEPTNO
FROM DEPT
ORDER BY DNAME, LOC, DEPTNO DESC;

SELECT DNAME DEPT, LOC AREA, DEPTNO
FROM DEPT
ORDER BY DNAME, AREA,DEPTNO DESC;

SELECT DNAME, LOC AREA , DEPTNO
FROM DEPT
ORDER BY 1, AREA, 3 DESC;

SELECT EMPNO, ENAME
FROM EMP
ORDER BY MGR;

SELECT EMPNO
FROM (SELECT EMPNO, ENAME FROM EMP ORDER BY MGR);

SELECT MGR
FROM (SELECT EMPNO, ENAME FROM EMP ORDER BY MGR);

SELECT JOB, SAL
        FROM EMP
GROUP BY JOB
    HAVING COUNT (*) > 0
ORDER BY SAL;

SELECT JOB
    FROM EMP
GROUP BY JOB
    HAVING COUNT (*) > 0
ORDER BY SAL;

SELECT JOB, SUM(SAL) SALARY_SUM
FROM EMP
GROUP BY JOB
HAVING SUM (SAL) > 5000
ORDER BY SUM (SAL);

SELECT PLAYER.PLAYER_NAME 선수명 , TEAM.TEAM_NAME 소속팀명
FROM PLAYER, TEAM
WHERE TEAM.TEAM_ID = PLAYER.TEAM_ID;

SELECT PLAYER.PLAYER_NAME 선수명 , TEAM.TEAM_NAME 소속팀명
FROM PLAYER INNER JOIN TEAM
ON TEAM.TEAM_ID = PLAYER.TEAM_ID;

SELECT PLAYER.PLAYER_NAME, PLAYER.BACK_NO, PLAYER.TEAM_ID
      ,TEAM.TEAM_NAME, TEAM.REGION_NAME
FROM PLAYER, TEAM
WHERE TEAM.TEAM_ID = PLAYER.TEAM_ID;

SELECT A.PLAYER_NAME 선수명, A.BACK_NO 백넘버, A.TEAM_ID 팀코드
      ,B.TEAM_NAME 팀명, B.REGION_NAME 연고지
FROM PLAYER A, TEAM B
WHERE B.TEAM_ID = A.TEAM_ID;


