SELECT A.PLAYER_NAME 선수명, A.BACK_NO 백넘버
      ,B.REGION_NAME 연고지, B.TEAM_NAME 팀명
      FROM PLAYER A, TEAM B
      WHERE A.POSITION = 'GK'
      AND B.TEAM_ID = A.TEAM_ID
ORDER BY A.BACK_NO;

SELECT PLAYER.PLAYER_NAME 선수명, A.BACK_NO 백넘버
      ,B.REGION_NAME 연고지, B.TEAM_NAME 팀명
      FROM PLAYER A, TEAM B
      WHERE A.POSITION = 'GK'
      AND B.TEAM_ID = A.TEAM_ID
ORDER BY A.BACK_NO;

SELECT TEAM.REGION_NAME, TEAM.TEAM_NAME, TEAM.STADIUM_ID
      , STADIUM.STADIUM_NAME, STADIUM.SEAT_COUNT
      FROM TEAM, STADIUM
WHERE STADIUM.STADIUM_ID = TEAM.STADIUM_ID;

SELECT A.REGION_NAME, A.TEAM_NAME, A.STADIUM_ID
      ,B.STADIUM_NAME, B.SEAT_COUNT
      FROM TEAM A, STADIUM B
WHERE B.STADIUM_ID = A.STADIUM_ID;

SELECT REGION_NAME, TEAM_NAME, A.STADIUM_ID
      , STADIUM_NAME, SEAT_COUNT
    FROM TEAM A, STADIUM B
WHERE B.STADIUM_ID = A.STADIUM_ID;

SELECT A.ENAME, A.JOB, A.SAL, B.GRADE
  FROM EMP A, SALGRADE B
WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL;

SELECT A.ENAME 사원명, A.SAL 급여, B.GRADE 급여등급
FROM EMP A, SAL_GRADE B
WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL;

SELECT A.PLAYER_NAME 선수명, A.POSITION 포지션
      ,B.REGION_NAME 연고지, B.TEAM_NAME 팀명
      ,C.STADIUM_NAME 구장명
    FROM PLAYER A, TEAM B, STADIUM C
    WHERE B.TEAM_ID = A.TEAM_ID
    AND C.STADIUM_ID = B.STADIUM_ID
ORDER BY  선수명;

SELECT A.STADIUM_NAME, A.STADIUM_ID, A.SEAT_COUNT, A.HOMETEAM_ID
      ,B.TEAM_NAME
      FROM STADIUM A, TEAM B
      WHERE B.TEAM_ID(+) = A.HOMETEAM_ID
ORDER BY A.HOMETEAM_ID;

SELECT A.ENAME, A.DEPTNO, B.DNAME, B.LOC
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO(+);

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A, DEPT B
WHERE B.DEPTNO = A.DEPTNO;

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A INNER JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

SELECT A.EMPNO, A.ENAME, DEPTNO, B.DNAME 
FROM EMP A NATURAL JOIN DEPT B;



