SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A NATURAL JOIN DEPT B;

SELECT
    *
FROM EMP A NATURAL JOIN DEPT B;

SELECT *
FROM EMP A INNER JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;

UPDATE DEPT_TEMP
    SET DNAME = 'CONSULTING'
WHERE DNAME = 'RESEARCH';

UPDATE DEPT_TEMP
    SET DNAME = 'MARKETING'
WHERE DNAME = 'SALES'

SELECT *
FROM DEPT_TEMP;

SELECT
    *
FROM DEPT A NATURAL INNER JOIN DEPT_TEMP B;

SELECT
    *
FROM DEPT A NATURAL JOIN DEPT_TEMP B;

SELECT
    *
FROM DEPT A JOIN DEPT_TEMP B
ON B.DEPTNO = A.DEPTNO
AND B.DNAME = A.DNAME
AND B.LOC = A.LOC;

SELECT
    *
FROM DEPT A JOIN DEPT_TEMP B
USING (DEPTNO);

SELECT A.DEPTNO, A.DNAME, A.LOC, B.DNAME, B.LOC
FROM DEPT A JOIN DEPT_TEMP B
USING (DEPTNO);

SELECT DEPTNO, A.DNAME, A.LOC, B.DNAME, B.LOC
FROM DEPT A JOIN DEPT_TEMP B
USING (DEPTNO);

SELECT *
FROM DEPT A JOIN DEPT_TEMP B
USING (DNAME);

SELECT *
FROM DEPT A JOIN DEPT_TEMP B
USING (LOC, DEPTNO);