SELECT
    *
FROM DEPT A JOIN DEPT_TEMP B
USING (DEPTNO, DNAME);

SELECT A.EMPNO, A.ENAME, B.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B
ON (B.DEPTNO = A.DEPTNO);

SELECT A.ENAME, A.DEPTNO, B.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B
ON B.DEPTNO = A.DEPTNO
WHERE B.DEPTNO = 30;

SELECT A.ENAME, A.MGR, A.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B
ON B.DEPTNO = A.DEPTNO
AND A.MGR = 7698;

SELECT A.ENAME, A.MGR, A.DEPTNO, B.DNAME
FROM EMP A JOIN DEPT B 
ON B. DEPTNO = A.DEPTNO
WHERE A.MGR = 7698;

SELECT A.TEAM_NAME, A.STADIUM_ID, B.STADIUM_NAME
FROM TEAM A JOIN STADIUM B
ON B.STADIUM_ID = A.STADIUM_ID
ORDER BY A.STADIUM_ID;

SELECT A.TEAM_NAME, STADIUM_ID, B.STADIUM_NAME
FROM TEAM A JOIN STADIUM B
USING (STADIUM_ID)
ORDER BY STADIUM_ID;

SELECT A.TEAM_NAME, A.TEAM_ID, B.STADIUM_NAME
FROM TEAM A JOIN STADIUM B
ON B.HOMETEAM_ID = A.TEAM_ID
ORDER BY A.TEAM_ID;

SELECT A.EMPNO, A.DEPTNO, B.DNAME, C.DNAME NEW_DNAME
FROM EMP A JOIN DEPT B
ON B.DEPTNO = A.DEPTNO
JOIN DEPT_TEMP C
ON C.DEPTNO = B.DEPTNO;

SELECT A.EMPNO, A.DEPTNO, B.DNAME, C.DNAME NEW_DNAME
FROM EMP A, DEPT B, DEPT_TEMP C
WHERE B.DEPTNO = A.DEPTNO
AND C.DEPTNO = B.DEPTNO;

SELECT A.PLAYER_NAME 선수명, A.POSITION 포지션
      ,B.REGION_NAME 연고지명, B.TEAM_NAME 팀명
      ,C.STADIUM_NAME 구장명
FROM PLAYER A JOIN TEAM B
ON B.TEAM_ID = A.TEAM_ID
JOIN STADIUM C
ON C.STADIUM_ID = B.STADIUM_ID
WHERE A.POSITION = 'GK'
ORDER BY 선수명;

SELECT A.PLAYER_NAME 선수명, A.POSITION 포지션
      ,B.REGION_NAME 연고지명, B.TEAM_NAME 팀명
      ,C.STADIUM_NAME 구장
FROM PLAYER A, TEAM B, STADIUM C
WHERE A. POSITION = 'GK'
AND B.TEAM_ID = A.TEAM_ID
AND C.STADIUM_ID = B.STADIUM_ID
ORDER BY 선수명;

SELECT B.STADIUM_NAME, B.STADIUM_ID, A.SCHE_DATE
      ,C.TEAM_NAME, D.TEAM_NAME
      ,A.HOME_SCORE, A.AWAY_SCORE
FROM SCHEDULE A JOIN STADIUM B
ON B.STADIUM_ID = A.STADIUM_ID
JOIN TEAM C
ON C.TEAM_ID = A.HOMETEAM_ID
JOIN TEAM D
ON D.TEAM_ID = A.AWAYTEAM_ID
WHERE A.HOME_SCORE >= A.AWAY_SCORE +3;

SELECT B.STADIUM_NAME, B.STADIUM_ID, A.SCHE_DATE
      ,C.TEAM_NAME, D.TEAM_NAME
      ,A.HOME_SCORE, A.AWAY_SCORE
FROM SCHEDULE A, STADIUM B, TEAM C, TEAM D
WHERE A.HOME_SCORE >= A.AWAY_SCORE +3
AND B.STADIUM_ID = A.STADIUM_ID
AND C.TEAM_ID = A.HOMETEAM_ID
AND D.TEAM_ID = A.AWAYTEAM_ID;

SELECT A.ENAME , B.DNAME
FROM EMP A CROSS JOIN DEPT B
ORDER BY A.ENAME;


