SELECT A.ENAME, B.DNAME
FROM EMP A CROSS JOIN DEPT B
WHERE B.DEPTNO = A.DEPTNO;

SELECT A.ENAME, B.DNAME
FROM EMP A INNER JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

SELECT A.STADIUM_NAME, A.STADIUM_ID, A.SEAT_COUNT, A.HOMETEAM_ID
     ,B.TEAM_NAME
     FROM STADIUM A LEFT OUTER JOIN TEAM B
     ON B.TEAM_ID = A.HOMETEAM_ID
ORDER BY A.HOMETEAM_ID;

SELECT A.STADIUM_NAME, A.STADIUM_ID, A.SEAT_COUNT, A.HOMETEAM_ID
     ,B.TEAM_NAME
     FROM STADIUM A LEFT JOIN TEAM B
     ON B.TEAM_ID = A.HOMETEAM_ID
ORDER BY A.HOMETEAM_ID;

SELECT A.ENAME, B.DEPTNO, B.DNAME, B.LOC
FROM EMP A RIGHT OUTER JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

SELECT A.ENAME, B.DEPTNO, B.DNAME, B.LOC
FROM EMP A RIGHT JOIN DEPT B
ON B.DEPTNO = A.DEPTNO;

UPDATE DEPT_TEMP
SET DEPTNO = DEPTNO + 20;

SELECT * FROM DEPT_TEMP;

SELECT * 
FROM DEPT A FULL OUTER JOIN DEPT_TEMP B
ON B.DEPTNO = A.DEPTNO;

SELECT * FROM DEPT A FULL JOIN DEPT_TEMP B
ON B.DEPTNO = A.DEPTNO;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
WHERE TEAM_ID = (SELECT TEAM_ID
                 FROM PLAYER
                 WHERE PLAYER_NAME = '정남일')
ORDER BY PLAYER_NAME;

SELECT PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
WHERE HEIGHT <= (SELECT AVG (HEIGHT) FROM PLAYER)
ORDER BY PLAYER_NAME;

SELECT REGION_NAME 연고지명, TEAM_NAME 팀명, E_TEAM_NAME 영문팀명
FROM TEAM
WHERE TEAM_ID = (SELECT TEAM_ID
                 FROM PLAYER
                 WHERE PLAYER_NAME ='정현수')
ORDER BY TEAM_NAME;

SELECT REGION_NAME 연고지명, TEAM_NAME 팀명,E_TEAM_NAME 영문팀명
FROM TEAM
WHERE TEAM_ID IN (SELECT TEAM_ID
                  FROM PLAYER
                  WHERE PLAYER_NAME='정현수')
ORDER BY TEAM_NAME;

SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
      ,BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE (TEAM_ID, HEIGHT) IN (SELECT TEAM_ID, MIN (HEIGHT)
                            FROM PLAYER
                            GROUP BY TEAM_ID)
ORDER BY TEAM_ID, PLAYER_NAME;

SELECT B.TEAM_NAME 팀명, A.PLAYER_NAME 선수명, A.POSITION 포지션
      ,A.BACK_NO 백넘버, A.HEIGHT 키
FROM PLAYER A, TEAM B
WHERE A.HEIGHT < (SELECT  AVG (X.HEIGHT)
                  FROM PLAYER X
                  WHERE X.TEAM_ID = A.TEAM_ID
                GROUP BY X.TEAM_ID)
    AND B.TEAM_ID = A.TEAM_ID
ORDER BY 선수명;