SELECT B.TEAM_NAME 팀명, A.PLAYER_NAME 선수명, A.BACK_NO 백넘버
FROM (SELECT TEAM_ID, PLAYER_NAME, BACK_NO
FROM PLAYER
WHERE POSITION = 'MF') A
, TEAM B
WHERE B.TEAM_ID = A.TEAM_ID
ORDER BY 선수명;

SELECT PLAYER_NAME 선수명, POSITION 포지션
      ,BACK_NO 백넘버, HEIGHT 키
FROM (SELECT PLAYER_NAME, POSITION, BACK_NO, HEIGHT
FROM PLAYER
WHERE HEIGHT IS NOT NULL
ORDER BY HEIGHT DESC)
WHERE ROWNUM <=5;

SELECT A.TEAM_ID 팀코드, B.TEAM_NAME 팀명
      , ROUND (AVG(A.HEIGHT), 3) 평균키
    FROM PLAYER A, TEAM B
   WHERE B.TEAM_ID = A.TEAM_ID
GROUP BY A.TEAM_ID, B.TEAM_NAME
  HAVING AVG (A.HEIGHT) < (SELECT AVG (X.HEIGHT)
                            FROM PLAYER X
                          WHERE X.TEAM_ID IN (SELECT TEAM_ID
                                                FROM TEAM
                                              WHERE TEAM_NAME = '삼성블루윙즈'));
                                              

SELECT PLAYER_NAME, POSITION, BACK_NO, TEAM_ID, TEAM_NAME
FROM V_PLAYER_TEAM
WHERE PLAYER_NAME LIKE '황%';

SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
     ,BACK_NO 백넘버, HEIGHT 키
   FROM PLAYER
  WHERE TEAM_ID = 'K02'
UNION
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
     ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
WHERE TEAM_ID = 'K07';

SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
     ,BACK_NO 백넘버, HEIGHT 키
   FROM PLAYER
  WHERE TEAM_ID = 'K02'
UNION
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
     ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
WHERE TEAM_ID = 'GK';

SELECT DISTINCT
       TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
       ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
   WHERE TEAM_ID = 'K02'
      OR POSITION = 'GK';

SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
      ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
   WHERE TEAM_ID = 'K02'
UNION ALL
SELECT TEAM_ID 팀코드 , PLAYER_NAME 선수명, POSITION 포지션
      ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
   WHERE POSITION = 'GK';
   
SELECT 팀코드, 선수명 , 포지션, 백넘버, 키, COUNT (*) 중복수
    FROM (SELECT TEAM_ID 팀코드,PLAYER_NAME 선수명
                 ,POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
            FROM PLAYER
           WHERE TEAM_ID = 'K02'
         UNION ALL
         SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명
               , POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
          FROM PLAYER
        WHERE POSITION = 'GK')
GROUP BY 팀코드, 선수명, 포지션, 백넘버 ,키
  HAVING COUNT (*) > 1;
  
SELECT 'P' 구분코드, POSITION 포지션, ROUND(AVG (HEIGHT), 3) 평균키
     FROM PLAYER
GROUP BY POSITION
UNION ALL
SELECT  'T' 구분코드, TEAM_ID 팀명, ROUND (AVG (HEIGHT), 3) 평균키
    FROM PLAYER
GROUP BY TEAM_ID
ORDER BY 1;

SELECT  TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
       ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
   WHERE TEAM_ID = 'K02'
MINUS
SELECT  TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션
       ,BACK_NO 백넘버, HEIGHT 키
    FROM PLAYER
   WHERE POSITION = 'MF'
ORDER BY 1,2,3,4,5;

