SELECT ENAME, HIREDATE, SAL
      , LAG (SAL,2,0) OVER (ORDER BY HIREDATE) LAG_SAL
      FROM EMP
    WHERE JOB = 'SALESMAN';
    
SELECT ENAME, HIREDATE
      , LEAD (HIREDATE, 1) OVER (ORDER BY HIREDATE) LEAD_HIREDATE
    FROM EMP
  WHERE JOB = 'SALESMAN';
  
SELECT ENAME, SAL
      , ROUND (RATIO_TO_REPORT (SAL) OVER (), 2) SAL_RR
    FROM EMP
  WHERE JOB = 'SALESMAN';
  
SELECT DEPTNO, ENAME, SAL
      , PERCENT_RANK () OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) PR
    FROM EMP;

SELECT DEPTNO, ENAME , SAL
     , CUME_DIST () OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) CD
     FROM EMP;

SELECT ENAME, SAL
      , NTILE (4) OVER (ORDER BY SAL DESC) NT
    FROM EMP;
    
SELECT ENAME, SAL
    FROM EMP
   WHERE ROWNUM < 4
ORDER BY SAL DESC;

SELECT ENAME, SAL
  FROM (SELECT  ENAME, SAL
            FROM EMP
        ORDER BY SAL DESC)
WHERE ROWNUM <= 3;

SELECT TOP(2)
       ENAME, SAL
    FROM EMP
ORDER BY SAL DESC;

SELECT TOP(2) WITH TIES
       ENAME, SAL
    FROM EMP
ORDER BY SAL DESC;