SELECT * 
    FROM (SELECT JOB, DEPTNO , SAL FROM EMP)
   PIVOT (SUM (SAL) FOR DEPTNO IN (10,20,30))
ORDER BY 1;

SELECT * 
FROM (SELECT TO_CHAR (HIREDATE, 'YYYY') AS YYYY, JOB , DEPTNO , SAL FROM EMP)
PIVOT (SUM(SAL) FOR DEPTNO IN (10,20,30))
ORDER BY 1, 2;

SELECT *
FROM (SELECT JOB , DEPTNO, SAL FROM EMP)
PIVOT (SUM (SAL) AS SAL FOR DEPTNO IN (10 AS D10, 20 AS D20, 30 AS D30))
ORDER BY 1;

SELECT JOB,D20_SAL
FROM (SELECT JOB, DEPTNO, SAL FROM EMP)
PIVOT (SUM (SAL) AS SAL FOR DEPTNO IN (10 AS D10 , 20 AS D20, 30 AS D30))
WHERE D20_SAL > 2500
ORDER BY 1;

SELECT *
FROM (SELECT JOB, DEPTNO, SAL FROM EMP)
PIVOT (SUM (SAL) AS SAL, COUNT (*) AS CNT FOR DEPTNO IN (10 AS D10, 20 AS D20))
ORDER BY 1;

SELECT *
FROM (SELECT TO_CHAR (HIREDATE, 'YYYY') AS YYYY, JOB ,DEPTNO , SAL FROM EMP)
PIVOT (SUM (SAL) AS SAL, COUNT (*) AS CNT
FOR (DEPTNO, JOB) IN ((10, 'ANALYST') AS D10A, (10, 'CLERK') AS D10C
                     ,(20, 'ANALYST') AS D20A, (20,'CLERK') AS DE20C))
ORDER BY 1;

SELECT JOB
      , SUM (CASE DEPTNO WHEN 10 THEN SAL END) AS D10_SAL
      , SUM (CASE DEPTNO WHEN 20 THEN SAL END) AS D20_SAL
      , SUM (CASE DEPTNO WHEN 30 THEN SAL END) AS D30_SAL
FROM EMP
GROUP BY JOB
ORDER BY JOB;

SELECT * FROM T1 ORDER BY JOB;

SELECT JOB,DEPTNO,SAL
    FROM T1
     UNPIVOT (SAL FOR DEPTNO IN (D10_SAL, D20_SAL))
ORDER BY 1 , 2;

